### ISSUE TITLE
Make redis an official rosdep

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#1]
If you haven't done it before, we've got some instructions on the Yujin redmine wiki:
- http://redmine.yujin.com/projects/open-resources/wiki/Rosdep

**Comment by jihoonl** [comment]
I have pushed into yujinrobot/rosdistro. I will wait for your confirmation before I do the pull request.

**Comment by stonier** [comment]
[Pull request #80](https://github.com/ros/rosdistro/pull/80)
