### ISSUE TITLE
Roll debs

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#103]
Don't catkinize yet, just roll some debs.

**Comment by piyushk** [comment]
Does groovy support non-catkinized debs? Also, I would not mind rolling out debs for Fuerte as well. The Fuerte -> Groovy transition will be a bit rough here, so it might be some time before I end up doing it.

**Comment by stonier** [comment]
Yes, groovy still supports non catkinized debs. Catkin is slowly getting mature, but groovy is still very much an iteration for catkin.

We can branch, do debs for both and cherrypick minor items from one branch to the other. It'll probably be a while before I do major development on this component again (e.g. multihub), and by that time you'll probably have caught up to groovy.

**Comment by stonier** [comment]
ach, closed by the wrong commit...

**Comment by stonier** [comment]
Pending and [rolling] debs: 
- **Fuerte**
  - rocon_multimaster, [zeroconf_comms], [zeroconf_avahi_suite], [rocon_comms]
- **Groovy**
  - rocon_multimaster, zeroconf_comms, zeroconf_avahi_suite, [rocon_comms]

**Comment by stonier** [comment]
Groovy debs are all rolling.

We're waiting on fuerte - they're not running jenkins fuerte build very often right now.

**Comment by stonier** [comment]
Fuerte debs are now building too.

**Comment by piyushk** [comment]
It looks like the fuerte debs got pushed to the release repository.
