### ISSUE TITLE
Gateways as regex patterns

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#108]
I imagine this would be a nice convenience as well, specially since we postfix gateway names with an incremental integer for uniqueness.

'pull all' for 'myrobot.*' becomes quite meaningfull.

**Comment by piyushk** [comment]
Definitely. Also I think this was already open #99, or did you mean something else?

I should be back on infrastructure development as soon as my struggle with Kinects and USB 3.0 ends.

**Comment by stonier** [comment]
Ach...too many things floating around my head!

Jihoon brought this up yesterday and I'd forgotten I'd opened that issue.

Thanks piyush.
