### ISSUE TITLE
Flipping Implementation

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#11]
Local flipping topics to a remote.

a. The remote gateway should be able to act like a firewall here
    1. Perhaps a boolean to start with, always ignore or always accept
    2. If accepting, it then passes a triple on to the master to register
    3. In rocon, concert master always accepts, app managers always ignore

b. flipping out a topic should not put it in the gateway’s public interface (you’re in control of where you want it to go)

c. flipping should involve:
    1. posting the triple on another gateway’s box on the redis server
    2. the other gateway has a callback which notices this
    3. then accepts or refuses to do so
    4. if accepts, it takes the triple and sends it to it’s local master

**Comment by jihoonl** [comment]
It is implemented.

Check out flipout_topic.py in rocon_gateway_test package for usage.

**Comment by jihoonl** [comment]
Still there is no method to unregister "flipped-out" topics/services.

**Comment by stonier** [comment]
Invalidating this, will recreate issues relevant to ideas from the [review](http://ros.org/wiki/rocon_multimaster/Reviews/Gateway_API_Review%20-%20Oct%202012).
