### ISSUE TITLE
Advertise and Remote

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#110]
AdvertiseReqeust allows to apply multiple rules.

RemoteRequest only allows to apply one rule.

It would be good if we use same style for both service call. Maybe make remote request have the similar format as advertise request.

Ex:
Remote.srv

string gateway
Rule[] rule
bool cancel

---

keep the same

**Comment by stonier** [comment]
Im fine with that.

**Comment by jihoonl** [comment]
Places to change:

gateway_comms and ...

jihoonl@whoolala:/opt/jihoonl/rocon/rocon_multimaster$ cfind RemoteRequest
./rocon_gateway_tests/tests/multimaster/pull_tutorials.py:31:        self.req = RemoteRequest() 
./rocon_gateway_tests/tests/multimaster/test_pull_remotely.py:80:            req = RemoteRequest()
./rocon_gateway_tests/tests/multimaster/test_pull_remotely.py:90:            req = RemoteRequest()
./rocon_gateway_tests/tests/multimaster/flip_tutorials.py:31:        self.req = RemoteRequest() 
./rocon_gateway/src/rocon_gateway/gateway_sync.py:190:          @type gateway_comms.srv.RemoteRequest
./rocon_gateway/src/rocon_gateway/gateway_sync.py:251:          @type gateway_comms.srv.RemoteRequest
./rocon_gateway_examples/scripts/flip_chatter.py:13:from gateway_comms.srv import Remote,RemoteRequest
./rocon_gateway_examples/scripts/flip_chatter.py:41:    req = RemoteRequest()

**Comment by stonier** [comment]
I broke yaml flips. 

I thought it would be simpler to specify gateway once in the service. But that just ends up being confusing - noticably so in the yaml settings.
