### ISSUE TITLE
IP in remote gateway info?

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#111]
Does it make sense to have the IP in the remote gateway info (ROS_IP)? This is extremely useful right now as we don't have an app manager yet. Once  a machine is connected, we SSH based on the IP address and launch applications.

You can currently get this information once you pull a connection from a foreign gateway and check the node_uri, but this method is a bit silly.

**Comment by stonier** [comment]
Sounds very useful.
