### ISSUE TITLE
Flipping a topic that is not registered yet.

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#113]
I am curious what happen if I want to flip a topic which does not exist yet.

for example,

-- Flip side -----------------------------------------
1. flip a publisher /chatter  
2. Wait 1 min  
3. starts  /talker node                         

-- on the other side --------------------------
1. ...
2.  /listener node started
3. ...

**Comment by stonier** [comment]
Should be fine. Important point - when you flip, you are not flipping a topic, you are adding a regex enabled _flip rule_.

1) It adds the flip rule to a watchlist
2) Immediately checks if it matches any existing connections and if yes, flips them
3) Checking the flip rule against existing connections is then done periodically in the watcher thread

So the above situation will usually take at most as long as the period of the watcher thread (default 20s I think).

Note that the period of the watcher thread is configurable as a gateway param. If you want really dynamic but high cost checking, set the period low, if you want to cater for a fairly static situation, set it to 5mins or so to reduce compatuational cost.
