### ISSUE TITLE
publishing gateway info as latched topic

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#114]
In current implementation, app_manager periodically poll /gateway/gateway_info to check the status of gateway.

Instead, if gateway feeds it's change of status by topic, it would be simpler to check gateway's status from app_manager.

**Comment by stonier** [comment]
Send full gateway info when there is a change (not just updates). This makes sure the listener is always correctly up to date.

**Comment by stonier** [comment]
Note, new fake service via latched subscriber function in rocon_utilities via dc9a8dc1f3cece58b9ef2341fa2ba5c220d80d7a!
