### ISSUE TITLE
Subscriber registrations not informing local publishers

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#125]
- Start gateway1, listener
- Start gateway2, talker
- Flip listener's /chatter to gateway2

Nothing happens
- Kill talker
- Restart talker

Presto - listener starts listening!

Maybe the master registration at gateway2 is not pinging the publishers when it registers a subscriber.

Let's dig into the master api.

**Comment by stonier** [comment]
As soon as you start a second talker (with different name), then both get shunted through.

**Comment by stonier** [comment]
Note gateway example cases

1) Talker connects, then listener connects. This is ok - listener calls master.registerSubscriber, checks it returns values and automatically (itself) connects to the publishers.

2) Listener connects, then talker connects. Talker first sends its information to the master, who relays publisher information to the subscriber via xmlrpc, where it makes the actual port connection (subscriber -> publisher).

Our problem case is 1), but it's a problem, because the node isn't doing the registering itself. We are doing that for it. So we have to parse the return value from the master and either write the connection code directly (not worth it), or alternatively, send it the connection information via xmlrpc as in 2). 

This seems to work.

Still some bugs in closing it down though - and have to thoroughly check actions as well.

**Comment by stonier** [comment]
Master is getting in the way sending updates requests to the subscriber - these provide a list of publisher uri's it should be connected to, but the problem is we have two masters. When either one sends one of these updates, it overrides the other's connections.

Slave api?

**Comment by stonier** [comment]
Slave api provides us with the actual list of connected publishers and we could maintain/fix it when doing flips/unflips. The real problem though is with the masters. As soon as we register a subscriber with them, it is at the mercy of notifications from the masters. This causes a problem - each notification completely obliterates any connections to publishers on other masters as the subscriber resyncs only with the local list of publisher connections.

I need to draw something for that to make sense.

It would be fine if these updates only carried additions, or removals, not the complete list of local publishers.

I suspect they did this to make it robust (i.e. if an update was missed, or connection error, then it will resync everything at next update) or it was just a lazy easy first implementation.

For now, it means flipping, pulling subscribers relies on the user restricting it's access to just one master at a time (either local or remote).

In January we'll talk with people about ways we can possibly remedy this situation. We should either wait for a comms engine redesign, or probably attack rospy's subscriber xmlrpc update/rosmaster notify methods.

**Comment by stonier** [comment]
Continue in #126

**Comment by piyushk** [comment]
Jihoon posted a bug report at the same time :). This is continued in https://github.com/robotics-in-concert/rocon_multimaster/issues/127
