### ISSUE TITLE
rocon_launch does not work in some environment

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#152]
All child terminal complain this

![rocon_fail](https://f.cloud.github.com/assets/1556736/384850/7ee3eb40-a669-11e2-83cf-ad3a79de2ba2.png)

**Comment by stonier** [comment]
Got more information on which environments? I can't reproduce it so I need access to the machine which is doing this.

**Comment by jihoonl** [comment]
Ubuntu precise. Asus x201e. Tested in adams.
Also same thing happend with Dongwook's virtual machine.

**Comment by stonier** [comment]
Throw the netbook at me in the morning :)

**Comment by stonier** [comment]
Wasn't inheriting the environment from the old shell. Worked on Jihoon's because he had environment settings in his `~/.bashrc`.

Fixed in 5542dc2dfaf92487a830aadbe9618efa5cd06f14 a2fe93a535f31cece3b20a14db69260cca66b9d9 and 1bc548d6530d17a1f450ab708105fd6a71a1d56f
