### ISSUE TITLE
Profiling Connection Builder

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#155]
This is killing us at the moment. With only a few connections, the call to master and the connection sorting/building takes only a couple of hundred milliseconds. Once we blow out to more than 50 connections, this takes two seconds (both recorded on the turtlebot pc). Thanks for pointing us towards some real data on this Jorge.

The loops in there were quick dirty prototypes. There is even some horrid nesting of loops inside each other.

This part needs to be optimised. Maybe even put in c code.

**Comment by stonier** [comment]
Test results for `LocalMaster.get_connection_state` on my home pc with `rocon_gateway_tests/tutorials_light.xml`:

```
  Pre-optimisation: ~9ms
```

With `tutorials_lightx2`:

```
  Pre-optimisation: ~120ms
```

With `tutorials_lightx7`:

```
  Pre-optimisation: ~470ms
```

**Comment by stonier** [comment]
Breakdown of 7x:

```
Benchmarks
  get_system_state: 0.0162558555603
  extract_action_servers: 0.000640153884888
  extract_action_clients: 0.000401020050049
  get_pubs: 0.105795860291
  get_subs: 0.0585739612579
  get_services: 0.189439058304
  get_action_servers: 0.052050113678
  get_action_clients: 0.0523898601532
  total_time: 0.475545883179
```

**Comment by stonier** [comment]
A test which helps get the cpu usage under load: `rocon_gateway_tests/bench_gateway_cpu.launch`. This starts the gateway under the following conditions:
- No zeroconf discovery (so the discovery thread shuts down)
- No default advertisements or flips or pulls

Running `top -p pid` on the gateway (get the pid from `ps axu`) with threads, `H` and command 'c' showing:

```
10290 snorri    20   0  440m  20m 4252 S 21.3  0.3   0:05.77 python 
10311 snorri    20   0  440m  20m 4252 S  0.0  0.3   0:00.00 python 
10312 snorri    20   0  440m  20m 4252 S  0.0  0.3   0:00.02 python 
10317 snorri    20   0  440m  20m 4252 S  0.0  0.3   0:00.00 python 
10343 snorri    20   0  440m  20m 4252 S  0.0  0.3   0:00.00 python 
```

Thread breakdown: `10290` is main (watcher), one from the redis listener thread and three from from rospy (rospy has one thread for each topic (regardless of number of subscribers).

That heavy thread ranges from `10-21%` and is the watcher thread. From this we can conclude the internal connection generation is a big culprit and the redis thread is almost nothing but we can't conclude yet that there may be other optimisations needed for the watchlists.

**Comment by stonier** [comment]
A note on the previous commit - thread cost is negligible compared to the problem we have. But it's one less thread which wasn't needed.

**Comment by stonier** [comment]
Just did a quick test - if i generate a connection cache that works under the assumption that nothing changes and start the gateway later - cpu usage drops to zero. It is definitely inside that connection state generator.

**Comment by stonier** [comment]
We were doing alot of unnecessary xmlrpclib calls in the master api. I do them again later when actually making a flip or pull, so it was unnecessary when building the local connection index.

Even without doing a cache, taking these calls out generates only 10% of the original cpu usage.
