### ISSUE TITLE
rocon_gateway_tests test failure

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#162]
http://jenkins.willowgarage.com:8080/view/Prerelease/job/prerelease-groovy-rocon_tutorials-rocon_multimas.../2/ARCH_PARAM=amd64,UBUNTU_PARAM=precise,label=prerelease/console

**Comment by stonier** [comment]
This is for the nosetest: test_connection_cache.py

with error:

```
 File "/tmp/test_repositories/src_repository/rocon_multimaster/rocon_gateway/src/rocon_gateway/master_api.py", line 16, in <module>
    import rostopic
ImportError: No module named rostopic
```

**Comment by stonier** [comment]
This should be fixed in dependencies now. Anyway, the stack is a very different structure. Reopen a new ticket if there is still a problem.
