### ISSUE TITLE
Only invite local clients

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#169]
When multiple people starts their own concert in the same network, clients often get invited to randomly selected concert.

Ex) Dongwook was testing chatter concert while Marcus was testing pairing mode. Marcus's app manager continuously get invited by Dongwook's concert master and launched talker.

**Comment by stonier** [comment]
Id rather this not be a default, but certainly a parameterisable feature.

**Comment by stonier** [comment]
Initial thought was a `auto_invite_local_only` parameter for the conductor. But that doesn't stop rogue conductors elsewhere stealing your app managers.

**Comment by stonier** [comment]
App managers need a whitelist/blacklist? This is certainly beyond the protection of gateway hub whitelist/blacklists.

**Comment by stonier** [comment]
App managers already have remote_controller_whitelist/blacklist. But actually this is not sufficient. Someone running chatter_concert on two computers will get mixups unless they explicitly set different concert names via the conductor.

Pain in the ass.

One option is to use a generic CONCERT_NAME environment variable people can set to uniquely identify default concert names for their system.

Another option is have a parameter for `local_remote_controllers_only` in the app manager. But how does it work out the remote controller is a local one?

**Comment by stonier** [comment]
Maybe via `gateway_info` and `remote_gateway_info` ip variables. However after testing, the local gateway variable in remote_gateway_info is showing localhost, remote gateways are showing the pc name rocon-donizetti.

Gateways write to the hub the `self._gateway.ip` which is rocon-donizetti. The gateway_info topic also publishes this.

**Comment by stonier** [comment]
Ok, app manager should be able to check local vs remote gateway ip now.

**Comment by stonier** [comment]
Continuing problem on the app platform: https://github.com/robotics-in-concert/rocon_app_platform/issues/79
