### ISSUE TITLE
rocon_launch: pass --screen down

### ISSUE THREAD

**Issue by bit-pirate** [robotics-in-concert/rocon_multimaster#172]
... to launchers launched by rocon_launch. Otherwise important information can be hidden, e.g. nodelets not being able to be loaded into the manager, because of namespace issues.

**Comment by stonier** [comment]
It doesn't do this? That's the only job of the `--screen` option

**Comment by bit-pirate** [comment]
Wait, I believe this might not be an issue of rocon_launch, but the app manager. Those problems with nodelets not being loaded and their _wait for service message_ not being shown only happened when starting (r)apps.

**Comment by stonier** [comment]
Ah, jihoon commented on it, but I don't know if he made the issue anywhere, or if it's even possible for the app manager to introspect itself to know if it's publishing to screen or not.

Follow up on the app manager side in https://github.com/robotics-in-concert/rocon_app_platform/issues/57

**Comment by stonier** [comment]
1d5fb7c89ce3a86dab40c8d4d803d7c14f67b1ea
