### ISSUE TITLE
should rocon multimaster use ROS_IP?

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#178]
I've started running tests on gateway robustness against network failures by running the following tests:
- Dropping the route to the outside world (retain IP address):

```
sudo route del default
```
- Dropping the network connection (includes IP address drop):

```
sudo ifdown wlan0
```

We'll have to see if any of these situations arise in the real world. In reality, I expect all problems to be close to the first point above, with the exception that the machine is unaware that the foreign host is unreachable. 

The second situation is extremely bad. Since I have set ROS_IP through a script for rocon_multimaster, the entire local ROS system uses this IP address. Loss of the IP led to a catastrophic failure of the local ROS system as well:

```
ERROR: Unable to communicate with service [/rosout/get_loggers], address [rosrpc://10.146.119.91:36903]
```

This leaves the system unable to do anything.

Should we decide to fix this problem, ROS_IP should be set to localhost and the gateway needs to be told or discover the external IP of the machine. Additionally the gateway will need to make sure that all information passed to the hub or other gateways uses the external IP instead of localhost.

Thoughts?

**Comment by stonier** [comment]
Are you talking about setting `export ROS_IP=localhost`? Does that actually work?

ROS_IP is critical to pubs and subs communicating across machines. I would have thought that would have been the same as not setting it when communicating across machines

Supposing your IP is 192.168.10.123, what if you add another localhost alias....e.g. in `/etc/hosts`,

```
192.168.10.123 localhost
```

**Comment by piyushk** [comment]
Yes, I am talking about using `export ROS_IP=localhost`, but as you've correctly said, it does not work right now. Getting it to work will involve a number of fixes to the multi-master chain. The main change will be replacing localhost (i.e. ROS_IP) with the external IP before passing information to the hub and other gateways.

I believe your solution won't work. As far as I see it maps localhost to the external IP address instead of 127.0.0.1, which should not make any difference. I believe it is possible to map the external IP address to 127.0.0.1, but it is extremely messy and requires system level permissions. I also don't know how to do it unless you are using network interfaces or an init.d script.

This issue is only important if your robot falls of the network, and your network setup attempts to rectify the issue by trying to connect to it again (and failing). If it can't get the IP address again (or get's a different IP address from a DHCP server), then the local ROS system goes down. Having ROS_IP as localhost solves these problems.

It is not clear whether this is necessarily something we need to worry about until we experience it.

**Comment by stonier** [comment]
Wouldn't ROS_IP=localhost cause roscpp communications to fail between machines?

**Comment by piyushk** [comment]
Yeah, you're right. I had to think about it for a bit, and it won't work. 

I'll think about this one for a bit. Have you experienced network outages with your robots? What happens in those situations (ifconfig, iwconfig, route -n)?

**Comment by stonier** [comment]
I've been avoiding investigating it. Yujin's robots only started getting into this some simple wireless activity to things like tvs previously - but that was not done with ros and the connections were never critical.

Time for some experiments this week and next I think.

**Comment by piyushk** [comment]
Ok. Let me know once you have some data on this. As far as I can tell We don't have wireless blind spots in our building, and I haven't lost connectivity yet.

**Comment by stonier** [comment]
I think our conclusions on this problem:

The wireless robot needs to use a name for ROS_HOSTNAME and either:
- Alias that name to 127.0.0.1 in `/etc/hosts` OR
- Use [split dns](http://en.wikipedia.org/wiki/Split-horizon_DNS) to serve 127.0.0.1 to the wireless machine

Everyone else needs dns server to serve the wireless machine's ip for the specified name.

@piyushk - do you agree?

**Comment by piyushk** [comment]
Yes. This seems right.

**Comment by stonier** [comment]
Shall we close this one?
