### ISSUE TITLE
rocon_hub_client and gateways should not independently try and detect when a hub goes down

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#179]
The gateway does this check [here](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_gateway/src/rocon_gateway/gateway_hub.py#L71).

The rocon_hub_client does this check [directly pinging the hub](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_hub_client/src/rocon_hub_client/hub_discovery.py#L120) or [detecting if the address is still available through zeroconf](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_hub_client/src/rocon_hub_client/hub_discovery.py#L132)

As far as I can see, it is quite possible that the gateway kicks the hub out, but the hub_discovery_client never tries to reestablish a connection once the hub becomes available again.

**Comment by stonier** [comment]
Yes true.

**Comment by piyushk** [comment]
ok. I'll work on this issue later this week.

**Comment by stonier** [comment]
For us, this is probably more important to consider it as when the gateway and hub lose connection - not when the hub goes down (we're assuming it's rock hard like the linux kernel!).

**Comment by piyushk** [comment]
bummer. redis_pubsub_server.listen() does not always raise ConnectionError when network connection to hub goes down (i.e. you dont ctrl+c the hub)
