### ISSUE TITLE
Gateway blacklist/whitelists

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#18]
Gateways should be able to block other gateways from flipping to them if they wish.

Don't exactly have a use for this yet - easier to just broadly blacklist/whitelist hubs (#25).

**Comment by stonier** [comment]
Let's just implement a  broad blocking policy flag against flip requests from anyone for now (i.e. stop remote gateways from entering the local system). We will need this for our app manager clients later - they should be a proper gateway firewalling anything from coming in.

**Comment by stonier** [comment]
Firewall flag in #83.
