### ISSUE TITLE
Redis clients for ARM

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#2]
From [redmine notes on redis](http://redmine.robotconcert.org/projects/multimaster/wiki/Redis), in particular [native compilation and testing](https://groups.google.com/forum/?fromgroups=#!topic/redis-db/4j_ohRJTD5g) and [cross-compiling](http://comments.gmane.org/gmane.comp.db.redis.general/9299).

The cross-compiling is less of an issue - we can always set up a native build server somewhere or I can patch his code if we want to solve that. The real question is whether there will be endianness issues.

**Comment by stonier** [comment]
Those comments, I think are for compiling the server?

**Comment by jihoonl** [comment]
Yes, these are form compiling the server from my understanding. One thing I noticed in the threads is that somebody pointed out a performance issue. It may perform poorly in ARM or android as a server.

**Comment by stonier** [comment]
Let's leave this one open too until we have a client actually running and working properly. If there is endianness issues, it may mean quite some work to fix things.

**Comment by johnnba** [comment]
hello everyone i'm also puzzled that are there any redis client on arm based wince system. thank you

**Comment by stonier** [comment]
Archiving.
