### ISSUE TITLE
What is correct behaviour for hub-gateway pinger

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#219]
**Relevant Code**
- [rocon_hub::Pinger](https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_hub/src/rocon_hub/watcher.py#L60)

_Current Funny Behaviour_

Steps to reproduce some funny behaviour
- Run a local gateway and hub
- Remotely run a remote gateway, discovers our hub
- Cut the wireless connection on the remote gateway.
- Kill the remote gateway (i.e. ctrl-c)
- Restart the remote network.

Currently the pinger on the hub will have not deleted the remote gateway information yet (because of the long timeout), and when the network restarts, it will ping with success again and positively list the remote gateway despite the fact that gateway software is no longer running on the remote machine.

_Desired Behaviour_

Should we implement some check after the ping to make sure there is a gateway there?

**Comment by stonier** [comment]
Could be used to clean up gateways that disappeared but haven't hit the looong timeout value on the hub when they reappear on the network without the gateway running.

**Comment by piyushk** [comment]
Excellent catch. We should definitely have a stronger check to make sure that the gateway is up.

Here's an alternative solution. How about we get the gateway to ping the hub? We already introduced the RedisConnectionChecker in #215, we can expand it to ping and collect ping latencies and store them on redis. As such, the hub sidekick will only be responsible for cleanup.

**Comment by stonier** [comment]
Had the same thought on the way home. Only tricky part would be in ensuring timestamps (last seen values) are synchronised since they no longer use the central hub pc to timestamp. Does redis itself have some sort of timestamping function?

**Comment by piyushk** [comment]
http://redis.io/commands

There seem to be a couple of ways:
1. Get the server time and use it to set time last seen
2. Set the key with a known expiration. The hub can figure out how long it has been by checking the TTL for the key.

Option 2 is probably better if the connection is shaky. We'll need to setup a constant in a separate connections message though.

**Comment by piyushk** [comment]
I have created a new ConnectionStatistics message. I am porting all code over to use that message, and will fix this issue in the process.

I have a spare laptop lying around. I'll install Ubuntu on it tonight. Should be good for testing tomorrow.
