### ISSUE TITLE
roconbash's zsh startup script references non-existent file

### ISSUE THREAD

**Issue by tlau** [robotics-in-concert/rocon_multimaster#227]
If I have rocon-utilities installed, any ros workspace I create generates the following error when sourcing devel/setup.zsh:

```
roslaunch /opt/ros/hydro/etc/catkin/profile.d/15.roconbash.zsh:.:3: no such file or directory: /opt/ros/hydro/share/rocon_utilities/roconzsh
```

Indeed, that file does not exist.  Simply touching it causes the error to go away, but I don't know if there's supposed to be something important in that file that didn't get committed to the repository.

Note that I'm using zsh, not bash. The problem doesn't happen with bash.

**Comment by stonier** [comment]
Missing install rule, thanks. Bugfixed in hydro/hydro-devel branches, and just bumped release to 0.6.2.

I have no idea if the zsh actually works though - have never had the opportunity to test it. Post an issue here if you run into problems.

**Comment by stonier** [comment]
@tlau Just out of curiousity, what are you trying to do with it?

Now is probably not a great time - hydro deb version is more of a 'show and tell' version and hydro-devel branch is getting worked on heavily at the moment (so stability is continually shifting and no docs). We will start incrementally releasing usable components from rocon in January, with hopefully a usable stack in beta for services/multi-robots in February.

**Comment by tlau** [comment]
@stonier I'm not actually using it. It just gets pulled in as a dependency for one of the other packages I'm using. So at best I hope it does no harm. :)

**Comment by stonier** [comment]
No problem.
