### ISSUE TITLE
Use socket timeouts on all redis connections

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#231]
I initially believed it was possible to get around this by properly shutting down each redis socket using socket.shutdown. Once you shut the socket down, RedisListenerThread exits gracefully in about 30 seconds.

However, a side-effect is that since socket.shutdown takes a bit of time, and redis.Connection.disconnect() is not exactly atomic, we sometimes try and close an already closed socket (and bad things happen). Currently, we are handling all raised exceptions in a hackish way (https://github.com/piyushk/rocon_multimaster/commit/78025ff169792148b629e773945d59026a12e677). If we use socket timeouts everywhere, this will become unnecessary.

**Comment by piyushk** [comment]
Relevant comment in code: https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_gateway/src/rocon_gateway/gateway_hub.py#L104

**Comment by stonier** [comment]
That's a nice informative comment! :neckbeard:

**Comment by piyushk** [comment]
Also found relevant bug report at py-redis: https://github.com/andymccurdy/redis-py/issues/225

If we introduce socket timeouts, we get rid of a few hacks (RedisConnectionChecker, manually disconnecting the connection pool, calling disconnect on a connection multiple times). On the flip side, we'll have to introduce a few hacks to work around the upstream issue above. Pushing a fix upstream is possible, but time-consuming, and I am not even sure what the correct behavior is supposed to be. 

Since the current behavior in hydro-devel is acceptable (#229 got fixed with socket shutdowns), I am marking this issue as wontfix. We can revisit it sometime in the future as necessary.
