### ISSUE TITLE
Error serializing field time_since_last_seen

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#233]
Can't work out who is throwing this and then printing the traceback. There is a commented line in the capabilities server which spits the error line 'Error processing request'  out, but this logging is showing up in the concert, which has no capabilities.

```
WARN] [WallTime: 1386650845.347717] Gateway : requested gateway info for unavailable gateway [duded3b848cc701a40558e3d2a0e5a0a4428]
[WARN] [WallTime: 1386650846.354354] Gateway : requested gateway info for unavailable gateway [dude23cdf7d747754a3594467d15a071a536]
Traceback (most recent call last):
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 622, in _handle_request
    transport.send_message(response, self.seq)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 605, in send_message
    serialize_message(self.write_buff, seq, msg)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/rospy/msg.py", line 152, in serialize_message
    msg.serialize(b)
  File "/mnt/ros/rocon/devel/lib/python2.7/dist-packages/gateway_msgs/srv/_RemoteGatewayInfo.py", line 390, in serialize
    except TypeError as te: self._check_types(te)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 311, in _check_types
    check_type(n, t, getattr(self, n))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 233, in check_type
    check_type(field_name+"[]", base_type, v)
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 243, in check_type
    check_type("%s.%s"%(field_name,n), t, getattr(field_val, n))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 243, in check_type
    check_type("%s.%s"%(field_name,n), t, getattr(field_val, n))
  File "/opt/ros/hydro/lib/python2.7/dist-packages/genpy/message.py", line 188, in check_type
    raise SerializationError('field %s must be an integer type'%field_name)
SerializationError: field gateways[].conn_stats.time_since_last_seen must be an integer type
[ERROR] [WallTime: 1386650846.363121] Error processing request: field gateways[].conn_stats.time_since_last_seen must be an integer type
None
Traceback (most recent call last):
```

**Comment by piyushk** [comment]
This is part of network statistics. I'll look at it right now. I am a bit confused as to what happened here. If I read this correctly, the value was None, which should not happen.

Piyush

**Comment by piyushk** [comment]
Just looked at the code. Some of the code assumes a float. Not sure why I have not seen this error before.

I need to grab my laptop. Fix ETA in about 15 minutes.

**Comment by stonier** [comment]
Just saw this same error with `field gateways[].ip`. So perhaps its unrelated to connection statistics.
- Thrown from `gateway_node.ros_service_remote_gateway_info(self, request)`
- There it calls `self._hub_manager.remote_gateway_info(gateway)`
- In hub_manager.py, this is calling hub.remote_gateway_info(remote_gateway_name)

Calls to hub instances are always protected by locks, so they should be safe. But the information written on the hub may not be.

**Comment by stonier** [comment]
Someone here is switching back and forth on wireless networks confusing the hell out of their avahi whilst running rocon. Fertile testing ground for gateway bugs :neckbeard:

**Comment by piyushk** [comment]
Avahi can do that. Yesterday when I was testing network outages and removed the hub from the network, avahi was quite insistent that the hub was alive. Even though the avahi-publish machine was down. Not sure how.

**Comment by stonier** [comment]
Looking at the remote gateway info retrieval:

https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_gateway/src/rocon_gateway/gateway_hub.py#L318

There is no protection here from retrieving rubbish data. In my case, failing to get the ip key would result in None and throw up the error immediately.

Perhaps need some way to validate against other users accidentally getting rubbish data on the hub.

**Comment by stonier** [comment]
:+1: for the fix on the int/float.

**Comment by piyushk** [comment]
I've opened #235.

I've got the parse_redis_\* functions. They return 0/False if the value is rubbish. You could probably add one for string and parse everything through that. I am not completely sure if these functions are required. I'll look at them again when I clean up the gateway_hub implementation after the demo. I need to look at pyredis for that.

**Comment by stonier** [comment]
The parse functions are nice. I put a guard in here instead to completely abort if the ip check is awry rather than send back basically an empty info data sheet. Should work for now.
