### ISSUE TITLE
Drop connections when remote gateway becomes unavailable

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#236]
If a remote gateway becomes unavailable (after 30 seconds), should we drop pulled and flipped-in connections from that gateway? We currently only do this once the gateway dies (defaults to 2 hours).

**Comment by stonier** [comment]
I don't yet have a strong argument for trying hard to remove them.

Except to keep the concert workspace clean I have no technical urgency to move on the matter. Maybe we can postpone it till such a technical reason arises?

**Comment by piyushk** [comment]
I agree. It might be useful if we don't implement explicit flip synchronizations, or start throwing flips around through the hub.

**Comment by piyushk** [comment]
We can open this up again if necessary. Since we're trying to introduce improved flip synchronizations, my original point for raising this issue no longer exists.
