### ISSUE TITLE
Set values on the hub when flipping connections

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#237]
We currently use the hub for advertisements and subscriptions, and redis channels for flips. During initial coding, this seemed natural.

I am now beginning to feel that this behavior is causing a number of synchronization issues. Any thoughts on writing flips to the hub as well, with the expectation that the remote gateway will pick them up from there? This should resolve a number of synchronization issues.

This would be a pretty massive change.

An alternative solution to synchronization would be for a remote gateway to ping against every flipped connection.

**Comment by piyushk** [comment]
I should mention that this solution will solve the synchronization issues in #213, the inability to use socket timeouts with redis in #231 (as we will no longer require pubsub.listen()).

**Comment by stonier** [comment]
Yeah, i've been pondering doing this for a while too. We can also add other information on the hub too - such as a reply with whether a flip was successful or not.

**Comment by piyushk** [comment]
That is exactly what I had in mind. I realized the advantages of this completely when I was testing gateway reconnectivity, and realized that pulls are already synchronized. I think I can still produces cases where flip synchronization will fail.

I can setup a test for this on my own branch sometime soon, and we'll see how well it works.

**Comment by stonier** [comment]
Ok...Also we're good to take new code again and test it whenever you wish.

**Comment by piyushk** [comment]
Here's a rough outline of what I have in mind. I'm mostly writing this as I've forgotten too much of the gateway code, and the list will help during implementation.

1) We'll drop RedisListenerThread and RedisConnectionCheckerThread (the sole purpose of which was to figure out when the RedisListenerThread got hung on listen if the connection went dead)
2) send_flip_request adds to the set 'flipped_in_connections' for the remote gateway. An 'enabled' field in the serialized connection information will be initialized to false.
3) Add FlippedInInterface (based on Interactive Interface) and update_flipped_in_interface to gateway.py
4) for every set member in flipped_in_connections, srem any member that has 'enabled' set to false, process the flip request. If an existing flipped_in connection no longer has an entry, unflip it.

I should be able to get to this later tonight.

**Comment by piyushk** [comment]
It seems that we're abusing FlippedInterface a bit. FlippedInterface.registrations stores information about flipped_in connections. I'll use this for now, and see if the functionality needs to be split later.

**Comment by stonier** [comment]
Just had an alarm bell go off in my head piyush. Do you think there is an issue with publicly posting flip information on the redis server? 

That would mean anyone could get the flip details and register them when actually only the target of the flip should be able to do so.

**Comment by piyushk** [comment]
Yes. The information can be read by anyone with access to redis. I've already got it implemented

How about using python-crypto for public/private encryption. Only the intended gateway will be able to decrypt the message.

**Comment by stonier** [comment]
How would the intended gateway unencrypt it? There would have to be some
key exchanging?

**Comment by piyushk** [comment]
I've run the following test successfully:
1) Each gateway generates a public/private key pair (RSA)
2) Publish the public key*
3) Gateways that want to flip to this gateway use this public key for encryption
4) Intended gateway can decrypt the message.

This works reasonably well except:
- Step #2 (the key exchange) is a problem right now. There is no way to verify the authenticity of the key. Someone can swap out the public key with their own and happily decode messages.

Additionally, our current pub/sub framework is not secure either. You can use the MONITOR command on redis to get a copy of messages sent. I suspect there are a number of other such issues that need to be tackled as well. 

How relevant is the security issue for you guys?

**Comment by stonier** [comment]
It's not relevant for us right now since it is not in a product yet, but I believe we should at least get the concept right (i.e. security for flips, don't care for advertisements) and a framework which lets us pop in the _right_ way of exchanging keys in the future if we need to.

To me, the above method looks ok for now. Once it's all working, let's make a document somewhere (probably start some sphinx documentation in the gateway) which explains what we were thinking about so we can easily revisit this in the future.
