### ISSUE TITLE
Option to not close windows.

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#238]
It is handy to debug.

**Comment by piyushk** [comment]
the windows still close if the roslaunch command itself fails. I'm not sure if it is worth fixing this, as no-terminals can be used for debugging.

**Comment by stonier** [comment]
I suspect when I hit this problem it will annoy me enough to invest some time in keeping roslaunch failed windows open ;)

**Comment by piyushk** [comment]
Errr. The hold feature does not seem to be working for me at all. I'm using Precise with gnome-terminal. I'll try to give a better report tomorrow.

**Comment by stonier** [comment]
I'll test at home tonight - I usually run with konsole, so gnome-terminal might be lacking a bit of TLC.

**Comment by stonier** [comment]
Tested, indeed didn't work for gnome terminals at all.
