### ISSUE TITLE
add flip status (pending/accepted/blocked)

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#255]
Flips now have a status associated with them. Do these 2 things:
- [x] Publish this status in messages.
- [ ] Improve the flips.test in rocon_gateway_tests to ensure that flips are accepted to ensure success. It took me a while to realize that test was only checking that flips were being sent, and consequently receiving a flip was not being tested.

**Comment by piyushk** [comment]
Flip status publishing introduced in https://github.com/piyushk/rocon_multimaster/commit/b326ddd439b4edf0a968aaa38e5281966d2cb2b2

**Comment by stonier** [comment]
Bugfixed a status problem in 216823f4 and added a test in 89834dde.

Closing!
