### ISSUE TITLE
testing pep8 conformance

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#257]
Is there an automated test that you guys run to test pep8 conformance for rocon code?

**Comment by stonier** [comment]
Ive slowly been updating code using pydev in eclipse to show me warnings. I believe mike and jacks roslint package can help with this too and would like to start slipping that into all of our packages. Feel free to experiment with that if you wish.

**Comment by piyushk** [comment]
Understood. I'll look into it. I've often noticed that I tend to introduce these issues in the code, specifically additional white-spaces.

**Comment by stonier** [comment]
Some comments re eclipse
- pep8 settings are in `Preferences->Pydev->Editors->Code Analysis`.
- It uses its own internal pep8 script
- This is a bit older than the roslint pep8 script and not so configurable (e.g. no --max-line-length)
- You can't redirect it to the new pep8 scripts (e.g. roslint's) either (jpython incompatibilities)

So we can't get pydev running the same pep8 as roslint. However I haven't noticed any big difference except the default line length (pydev: 80, roslint: 120). I generally try and conform to that too these days, but you can always set --ignore=E501 in the eclipse settings and postcomment `# noqa` to a line if you want roslint to ignore it.

**Comment by stonier** [comment]
Just got roslint working on `rocon_interactions`. It's good! Nice way to help the other guys on the team make sure they parse for python errors or pep8 before pull requesting.

**Comment by piyushk** [comment]
I take it the 120 character line length is fine by you? I am adding roslint targets to all packages in this repo.

**Comment by piyushk** [comment]
rocon_gateway had 284 errors and warnings...

Autopep8 cuts it down to about 13:

```
sudo pip install autopep8
autopep8 --max-line-length 120 --in-place scripts/*
autopep8 --max-line-length 120 --aggressive --aggressive --in-place src/rocon_gateway/*.py
```

See https://pypi.python.org/pypi/autopep8/ for the definition of aggressive changes. Remaining 13 errors were resolved by hand. I then ran through all the changes using meld, and fixed some of the auto line-wraps. Most of the changes seem sane.

**Comment by stonier** [comment]
> I take it the 120 character line length is fine by you? 

Yep, that's ok.
