### ISSUE TITLE
pep8 conformance

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#259]
All packages in this repository should conform to pep8. To enable automated testing:
- Add a build dependency on roslint:

```
<build_depend>roslint</build_depend>
```
- Enable roslint macros and call them:

```
find_package(catkin REQUIRED COMPONENTS roslint)
...
# Lint Python modules for PEP8 compatibility
file(GLOB_RECURSE ${PROJECT_NAME}_PY_SCRIPTS
     RELATIVE ${PROJECT_SOURCE_DIR} scripts/*)
file(GLOB_RECURSE ${PROJECT_NAME}_PY_SRC
RELATIVE ${PROJECT_SOURCE_DIR} src/${PROJECT_NAME}/*.py)
roslint_python(${${PROJECT_NAME}_PY_SCRIPTS})
roslint_python(${${PROJECT_NAME}_PY_SRC})
```
- Test pep8 conformance using:

```
catkin_make roslint_<package_name>
```

To automatically cut down a lot of errors:

```
sudo pip install autopep8
autopep8 --max-line-length 120 --in-place scripts/*
autopep8 --max-line-length 120 --in-place src/<package-name>/*.py
```

You can also try the --aggresive for more aggresive correction. See `autopep8 --help`.

**Comment by stonier** [comment]
@piyushk moving this thread to the rocon repo where everyone can refer to as it's relevant for all rocon repos.

https://github.com/robotics-in-concert/rocon/issues/12
