### ISSUE TITLE
gateways should not generate a new public/private key pair every time they connect or re-connect to the hub

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#260]
If a gateway loses connectivity from the hub and reconnects, it generates a new (and different) public/private keyset. All old flips become useless and the gateway crashes trying to decrypt them.

**Comment by piyushk** [comment]
Even generating the gateway key at startup is insufficient if gateway uuids are disabled, as that gateway will not be able to access flip data on the hub under its name. I'm almost tempted to disable encryption for now, but I guess I'll add some codes to resend flips.

**Comment by stonier** [comment]
> Even generating the gateway key at startup is insufficient if gateway uuids are disabled, as that gateway will not be able to access flip data on the hub under its name. 

Not sure I follow this. Can you elaborate?

**Comment by piyushk** [comment]
If a gateway with uuids disabled crashes and restarts, it cannot generate the same public/private key that it used previously. Since uuids are disabled, it's going to try to access flips from the previous run which still exist on the database. It will not be able to decrypt these flip requests.

PR https://github.com/robotics-in-concert/rocon_multimaster/pull/261 solves this by getting a gateway to check for an existing public key in the database against its name. If the key exists, and does not match the public key the gateway has, then it requests a resend on all the flips.

**Comment by stonier** [comment]
Not sure I follow still, doesn't a gateway with uuid's also generate a different public/private key?

https://github.com/piyushk/rocon_multimaster/blob/fix_flip_encryption/rocon_gateway/src/rocon_gateway/utils.py#L237

**Comment by piyushk** [comment]
A gateway with uuids does not have access to old data on the hub. All pulls/flips need to be re-done and it is fine.

When a gateway without a uuid (gateway1) comes back up, it tries to re-access `rocon:gateway1:flip_ins`, which are encrypted with a key it does not have. These flips need to be resent with the new key.

**Comment by stonier** [comment]
Ah, clear. Thanks for breaking through the thick haze of pre-coffee indeterminism :neckbeard:
