### ISSUE TITLE
Gateway cpu usage high

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#267]
Seeing high usage (60% per gateway) on piyush's simulation. Get the chatter concert usage for a good reference and then consider attacking the problem. Gateways should be well under 10%.

**Comment by piyushk** [comment]
In case the chatter concert usage is high as well, there may be some possibility that this was a result of all the changes I made last month. 

Another possibility is that I set gateway_watch_loop_period to 1s https://github.com/piyushk/concert_services/blob/hydro-devel/concert_service_gazebo/launch/robot.launch, but this should be true for turtle concert as well, from where I ripped off the file.

**Comment by stonier** [comment]
```
28975 snorri    20   0  660m  21m 4420 S 49.5  0.3   0:27.14 python /mnt/zaphod/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py __name:=gateway __log:=/home/snorri/.ros/log/5880b
17645 root      20   0  658m 265m 182m R 23.1  3.3 135:17.41 /usr/bin/X :0 vt7 -br -nolisten tcp -auth /var/run/xauth/A:0-R3BO5a                                                                   
17841 snorri    20   0  809m  81m  31m S  8.6  1.0  50:31.76 kwin -session 1014e144d7d7000138589885000000020770000_1397808919_473021                                                               
28407 snorri    20   0  430m  41m  30m R  5.9  0.5   0:03.64 konsole -p tabtitle=dude:11314 --nofork --hold -e /bin/bash -c roslaunch --screen --disable-title --port 11314 /tmp/tmpg16Js5         
28405 snorri    20   0  430m  41m  29m S  5.3  0.5   0:03.56 konsole -p tabtitle=dudette:11312 --nofork --hold -e /bin/bash -c roslaunch --screen --disable-title --port 11312 /tmp/tmp7myRCo      
28406 snorri    20   0  430m  41m  29m S  5.3  0.5   0:03.57 konsole -p tabtitle=dude:11313 --nofork --hold -e /bin/bash -c roslaunch --screen --disable-title --port 11313 /tmp/tmphF_YSO         
29901 snorri    20   0  416m  14m 3608 S  2.0  0.2   0:00.32 python /opt/ros/hydro/share/rospy_tutorials/001_talker_listener/listener chatter:=/conversation/chatter __name:=listener __log:=/home/
28947 snorri    20   0  660m  20m 4416 S  1.6  0.3   0:01.67 python /mnt/zaphod/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py __name:=gateway __log:=/home/snorri/.ros/log/59771
27620 snorri    20   0 18008 1952 1040 R  1.3  0.0   0:02.10 top                                                                                                                                   
28853 snorri    20   0  660m  20m 4416 S  1.3  0.3   0:01.92 python /mnt/zaphod/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py __name:=gateway __log:=/home/snorri/.ros/log/59ac6
28962 snorri    20   0  660m  20m 4412 S  1.3  0.3   0:01.73 python /mnt/zaphod/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py __name:=gateway __log:=/home/snorri/.ros/log/58a7d
 1890 root      20   0  189m 4040 2960 S  1.0  0.0  27:36.36 /usr/lib/udisks/udisks-daemon                                                                                                         
29353 snorri    20   0  660m  21m 4420 S  1.0  0.3   0:00.40 python /mnt/zaphod/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py __name:=gateway __log:=/home/snorri/.ros/log/5880b
17850 snorri    20   0 1244m 135m  48m S  0.7  1.7  22:12.59 /usr/bin/plasma-desktop                                                                                                               
29047 snorri    20   0  660m  20m 4416 S  0.7  0.3   0:00.35 python /mnt/zaphod/ros/rocon/src/rocon_multimaster/rocon_gateway/scripts/gateway.py __name:=gateway __log:=/home/snorri/.ros/log/59771
29880 snorri    20   0  416m  14m 3608 S  0.7  0.2   0:00.29 python /opt/ros/hydro/share/rospy_tutorials/001_talker_listener/listener chatter:=/conversation/chatter __name:=listener __log:=/home/
32629 snorri    20   0 3868m 623m  68m S  0.7  7.8  11:37.03 /usr/bin/amarok                                                    
```

**Comment by stonier** [comment]
Interesting point here, only the concert gateway is busy. So that leads me to conclude it's not the runtime activity of the gateway, rather it must be getting busy handling callbacks (from the conductor probably). I need to check:
- [x] Conductor isn't inadvertantly spamming it
- [x] Whatever callback is handling the conductor's requests isn't too intensive (maybe cache some things?).
- [x] Check conductor v1 usage on hydro-devel

**Comment by stonier** [comment]
Conductor v1 usage is pretty high as well. Not quite as high, but still high.

**Comment by stonier** [comment]
It's not spamming it, it's only 1 remote_gateway_info service call per second.

It's also not intensive - that callback only runs for <10ms every second, which couldn't possibly raise the cpu rates we're seeing.

So my assumption is wrong. Something internally is blowing up the cpu and it is the runtime. Which now reminds me that I had all sorts of exponentially increasing cpu problems the more rules there were for a gateway to handle. This gateway is handling alot of pull rules, 5 for each robot on top of the flips etc.

**Comment by stonier** [comment]
- [ ] are the gateway loop algorithms heavy and can they be optimised
- [ ] heuristics, e.g. if a rule is triggered once, regardless of other factors, don't keep looking
- [x] conductor doesn't actually need so many pulls - most of these can go once it has it's information.
- [ ] get the conductor to slow down it's watcher loop period after it's been running a while.

**Comment by stonier** [comment]
For reference, the concert gateway running chatter concert on my work pc runs at 17-35%.

Use top, with `H` and `c`, or even better, `top -H -c -d 0.1 -p30882` substituting the appropriate delay and pid

**Comment by stonier** [comment]
Actually removing all those pulls (12 to 3) didn't change the cpu usage at all, still 17-35%.

**Comment by stonier** [comment]
Time diffs for the functions in the [watcher thread](https://github.com/robotics-in-concert/rocon_multimaster/blob/indigo/rocon_gateway/src/rocon_gateway/watcher_thread.py#L64):
- watcher diffs [0.01 0.01 0.01 0.02 0.02 0.02 0.07 0.56 ]

That last one is coming from `Gateway.update_flipped_interface`

**Comment by stonier** [comment]
Almost all this time is consumed in the scope of this [else block](https://github.com/robotics-in-concert/rocon_multimaster/blob/indigo/rocon_gateway/src/rocon_gateway/gateway.py#L333). Each call to `hub.accept_flip_request()` takes about 50ms. And if there are 8x flipped in connections to check, then it takes the 400-500ms we are looking at. Chatter concert is simple, this is going to die in a complicated scenario with many flipins.

Not actually doing any work here, just validating the existing connections, but I expect the serialization is being greedy. @piyushk do you have an idea of how to better do this? Is it necessary...I've removed it but are there possible situations we have to be careful of?

**Comment by stonier** [comment]
I didn't look inside `hub.accept_flip_request()` in detail and am just assuming its serializing/deserializing heavily for 50ms. Perhaps there is more to the story there.

**Comment by piyushk** [comment]
Well. I just did a rather poor implementation of `hub.accept_flip_request()`.Additionally, that else block is really nasty, as it tries to mark the flip as accepted even if it might be marked already.

Should be an easy fix, and should give considerable runtime improvement. I'll submit a PR later tonight.

**Comment by piyushk** [comment]
This has gotten pushed to tomorrow. Should be first thing on my list.

**Comment by stonier** [comment]
ok

**Comment by piyushk** [comment]
The time for `update_flipped_in_connections` for the gazebo_segbot_concert scenario has gone down from 0.45 to 0.0005 on my machine. See PR #268.

There are still a ton of steps that can be taken to clean up the base gateway infrastructure, both in terms of readability and efficiency. We'll get to them as time permits :grin:.

**Comment by stonier** [comment]
Tests well here, and pull request merged :neckbeard:
