### ISSUE TITLE
Flipping custom msg type topic/service

### ISSUE THREAD

**Issue by jihoonl** [robotics-in-concert/rocon_multimaster#27]
It may require msg/srv implementation on the remote side too.
Probably for action as well.

**Comment by stonier** [comment]
To get systems to update and retrieve possibly missing messages and services, would require alot of infrastructure. We shouldn't do that until the communications type is fixed well and stable (either ros will change in the next one or two versions or we will).

So the best thing we can do is to leave it up to the higher level layer (whether that is fkie or app manager or piyush's) to handle it and just provide them with very clear error messages when things go wrong.

**Comment by jihoonl** [comment]
There is a rosapi package from rosbridge_suite which provides services to get all topics and services details.
Using this, we may be able to create the custom type message on the remote side. 

For the information, I attached the list of services that rosapi provides,

/rosapi/delete_param
/rosapi/get_param
/rosapi/get_param_names
/rosapi/get_time
/rosapi/has_param
/rosapi/message_details
/rosapi/nodes
/rosapi/publishers
/rosapi/search_param
/rosapi/service_host
/rosapi/service_node
/rosapi/service_providers
/rosapi/service_request_details
/rosapi/service_response_details
/rosapi/service_type
/rosapi/services
/rosapi/set_param
/rosapi/subscribers
/rosapi/topic_type
/rosapi/topics
/rosapi/topics_for_type
/rosout/get_loggers
/rosout/set_logger_level

**Comment by stonier** [comment]
Archiving this - for the foreseeable future this is resolved by people making sure their systems are up to date with the latest rosdistro releases.
