### ISSUE TITLE
hub watcher does not recover from wireless lost state

### ISSUE THREAD

**Issue by dwlee** [robotics-in-concert/rocon_multimaster#271]

**Comment by piyushk** [comment]
@dwlee: Could you provide instructions to reproduce this error?

**Comment by jihoonl** [comment]
It was actually me. and I have showed @stonier how and what it happens. 

I have noticed that gateway wireless status never get recovered from missing status even though other topic channels are alive and working well.

**Comment by stonier** [comment]
We were checking via `remote_gateway_info` and remote gateways continually showed up as missing, even when they came back in range and ros topics started interacting again.

@piyushk I'll do some testing here and if it's not simple I'll ping you about it when we discuss the gazebo issues.

**Comment by stonier** [comment]
Testing results....

**Local Machine**

`local.launch`

```
<launch>
  <include file="$(find rocon_gateway_tests)/launch/common/primary_hub.xml"/>
  <include file="$(find rocon_gateway_tests)/launch/common/local_gateway.xml"/>
  <include file="$(find rocon_gateway_tests)/launch/common/talker.xml"/>
  <node ns="zeroconf" pkg="zeroconf_avahi" type="zeroconf" name="zeroconf"  output="screen"/>
</launch>
```

`/etc/hosts` (or DNS server)

```
192.168.10.213 inno
```

environment variables:

```
ROS_MASTER_URI=http://192.168.10.124:11311
ROS_IP=192.168.10.124
```

**Remote Machine (Laptop)**

`remote.launch`

```
<launch>
  <include file="$(find rocon_gateway_tests)/launch/common/remote_gateway.xml"/>
  <include file="$(find rocon_gateway_tests)/launch/common/listener.xml"/>
  <node ns="zeroconf" pkg="zeroconf_avahi" type="zeroconf" name="zeroconf"  output="screen"/>
</launch>
```

`/etc/hosts`

```
127.0.1.1     inno
```

environment variables:

```
ROS_MASTER_URI=http://localhost:11311
ROS_HOSTNAME=inno
```

**Results**

All ok, :+1: 
- Started both
- Local talker flipped
- Talker-Listener chatted no problem
- Disabled wireless on the remote laptop
- Chatting immediately stopped.
- `remote_gateway_info` (run on local machine) showed the `Alive` status as False after 30secs.
- Re-enabled wireless on the remote laptop.
- Chatting restarted
- `remote_gateway_info` switched back `Alive` status to True.

**Actions**

@jihoonl we need to sit down and work through your use case. Perhaps there is some easy to miss configuration going wrong here we need to fix or provide better feedback on.

**Comment by stonier** [comment]
Problem occurs when you walk away out of range and come back, but not when you just disable-enable the wireless on a laptop.

**Comment by piyushk** [comment]
@stonier I'll set up an internal wifi tomorrow to test it out as well.

**Comment by stonier** [comment]
I think I got it Piyush, it's a zeroconf issue.

```
[ INFO] [1399959005.395914475]: I heard: [hello world 1426]
[INFO] [WallTime: 1399959010.947200] DJS : hub connection checker thread exiting                                 [ gateway_hub  HubConnectionChecker  run()                      ]
[INFO] [WallTime: 1399959010.948261] Gateway : lost connection with hub, attempting to disconnect...             [ gateway_hub  GatewayHub            hub_connection_lost_hook() ]
[INFO] [WallTime: 1399959010.949015] Gateway : lost connection to the hub [Primary Hub][192.168.10.124:6380]     [ hub_manager  HubManager            disengage_hub(hub)         ]
[INFO] [WallTime: 1399959011.186147] Gateway : discovered hub via zeroconf [192.168.10.124:6380]
[INFO] [WallTime: 1399959011.875734] DJS : hub connection checker thread exiting
[INFO] [WallTime: 1399959011.876689] Gateway : lost connection with hub, attempting to disconnect...
[WARN] [WallTime: 1399959012.189137] Gateway : failed to register gateway with the hub [12][couldn't connect to the redis server]
[ INFO] [1399959021.555413111]: Zeroconf: service was removed [Primary Hub][_ros-multimaster-hub._tcp][local][3][ipv4]
[ INFO] [1399959057.521969843]: Zeroconf: discovered new service [Primary Hub][_ros-multimaster-hub._tcp][local][3][ipv4]
[ INFO] [1399959058.022456923]: Zeroconf: resolved service [Primary Hub][_ros-multimaster-hub._tcp][local][3][ipv4][192.168.10.124:6380]
```

Key lines are the immediate [discovered hub via zeroconf](https://github.com/robotics-in-concert/rocon_multimaster/blob/abde73e0faa02950953deaf78c6eb86c4b173d3b/rocon_hub_client/src/rocon_hub_client/hub_discovery.py#L99) and [failed to register gateway](https://github.com/robotics-in-concert/rocon_multimaster/blob/abde73e0faa02950953deaf78c6eb86c4b173d3b/rocon_gateway/src/rocon_gateway/gateway_node.py#L158).

**Comment by stonier** [comment]
English explanation:
- Wireless goes out of range
- HubConnectionChecker triggers a disengaging the hub
- While disengaging, the hub gets removed from the discovery thread's zeroconf list of hubs
- Avahi however, doesn't remove it for some 15-20 seconds
- Before avahi removes it, the discovery thread discovers it anew
  - ...but can't resolve it
- Our original policy is to put unresolvable hubs into a [blacklist](https://github.com/robotics-in-concert/rocon_multimaster/blob/abde73e0faa02950953deaf78c6eb86c4b173d3b/rocon_gateway/src/rocon_gateway/gateway_node.py#L156)
- On the next scanning opportunity, it begins ignoring our hub on the blacklist

**Comment by stonier** [comment]
I think the correct solution here is just to remove that blacklist policy. i.e. remove `HUB_CONNECTION_UNRESOLVABLE` from the [disallowed error codes](https://github.com/robotics-in-concert/rocon_multimaster/blob/abde73e0faa02950953deaf78c6eb86c4b173d3b/rocon_gateway/src/rocon_gateway/gateway_node.py#L61) and [reasons not to keep scanning](https://github.com/robotics-in-concert/rocon_multimaster/blob/abde73e0faa02950953deaf78c6eb86c4b173d3b/rocon_hub_client/src/rocon_hub_client/hub_discovery.py#L84).
