### ISSUE TITLE
UDP communication between different ROS networks

### ISSUE THREAD

**Issue by garaemon** [robotics-in-concert/rocon_multimaster#295]
Is it possible to communicate different ROS networks on UDP by using rocon?

**Comment by jihoonl** [comment]
rocon is just setting up channels among multiple ros masters. The actual communication is via ros communication layer. So UDP should be possible as roscpp supports it.

**Comment by garaemon** [comment]
Does this document describe how rocon works?
http://wiki.ros.org/rocon_gateway_tutorials/Tutorials/indigo/Flipping

**Comment by stonier** [comment]
That just describes one method of getting ros communications from one master to another master.

Rocon uses this tool, but there are many other concepts in Rocon too.

**Comment by stonier** [comment]
Just for reference, the answer here was yes...roscpp udp is certainly possible. To flip python topics (no udp in rospy), just drop in the ros relays and flip that.

Closing this :)
