### ISSUE TITLE
invalid ROS names

### ISSUE THREAD

**Issue by asmodehn** [robotics-in-concert/rocon_multimaster#336]
Need to be careful : as per specification [ROS name format](http://wiki.ros.org/Names) != [hostname format](https://en.wikipedia.org/wiki/Hostname).

Currently rocon uses hostname as robot name, but this should be properly formatted before.
We should probably have warning in multiple places to check for validity of ros names...

The effect of using an invalid ROS name are still not clear.
A warning message will be displayed by ROS : 

```
UserWarning: '/concert/clients/alexv-robotsim/battery' is not a legal ROS graph resource name. This may cause problems with other ROS tools
  super(Subscriber, self).__init__(name, data_class, Registration.SUB)
```

**Comment by asmodehn** [comment]
Note : I was able to flip topics that contained a dash '-', so this warning should not prevent from flipping topics.

**Comment by stonier** [comment]
Dashed topic will ultimately be unusable,  regardless

**Comment by stonier** [comment]
Closing this, the ros warning message is enough.
