### ISSUE TITLE
redis-server 3.0.6 not supported

### ISSUE THREAD

**Issue by mistoll** [robotics-in-concert/rocon_multimaster#346]
Hub reports a problem:
> [INFO] [1479740280.194106]: Hub : version 3.0.6
> [FATAL] Hub : the version of the redis server you have installed is not supported by rocon.
> [FATAL] Hub : please submit a ticket at https://github.com/robotics-in-concert/rocon_multimaster

3.0.6 is the only version available with ubuntu xenial.

**Comment by stonier** [comment]
I'll be doing a big trim of the rocon software for xenial in a couple of weeks so that we have a usable (and now robustified) gateway and app framework properly ready for xenial. I'll keep this one in mind.

**Comment by stonier** [comment]
Now in devel via bb45436d and ba2bee9a

More fixes coming for kinetic in the kinetic_updates branch.
