### ISSUE TITLE
Handling the zeroconf dependency

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#39]
This one is awkward to get right and there are a few issues:
- Zeroconf is optional in the hub/gateway
- Zeroconf is provided by different implementations on different platforms
- Zeroconf autostart on ubuntu sometimes gets smacked by a badly misbehaving isp

_Zeroconf as an optional dependency_

There are two places this needs to be addressed - in the rosdeps and in the stack dependencies. Ros doesn't provide any way to handle optional dependencies, so we need to make a call and just say we are handling them since the option by default is True.

_Zeroconf Platform Dependant Implementations_

Rosdeps : let's create a meta-tag for 'zeroconf' which will choose the right dependencies for the platform.

Ros Stack Deps: can't simply point to zeroconf_avahi, because that's a fail on most platforms. Really need to robustify our code with respect to things like import checks AND create higher level meta packages for the hub - e.g. rocon_gateway_hub_windows etc.

_Zeroconf Autostart on Ubuntu_

Big error messages currently. But this is not a good out of the box solution. We may need to check and run our own configured avahi daemon if the users' avahi daemon is not running?

**Comment by jihoonl** [comment]
- Zeroconf Autostart on Ubuntu temporary fix.
  Set AVAHI_DAEMON_DETECT_LOCAL=0 in /etc/default/avahi-daemon to resolve ISP conflict in the network.

**Comment by stonier** [comment]
Duplicate of #34
