### ISSUE TITLE
Redis clients for iphone/android

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#4]
Actually guarantee we have redis clients (and specifically which libraries they use) that work without hackery on iphone/android.

**Comment by jihoonl** [comment]
It works using JRedis(https://github.com/alphazero/jredis) on android. However, there may be performance issue.

ObjCHiredis(https://github.com/lp/ObjCHiredis) is an official object c redis client library. It is a Static Library for iOS4 device and Simulator, plus Objective-C Framework for MacOS 10.5 and higher This also may work with iOS5 and iOS6.

One other approach would be web-app that is using node.js redis client library.

**Comment by stonier** [comment]
Performance Issues?

Let's keep this issue open until we actually have a test executing. Seeing is believing!

**Comment by stonier** [comment]
Archiving.
