### ISSUE TITLE
Implement Actions

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#44]
They're just a bundle of pubsubs, shouldn't be too hard (famous last words).

**Comment by stonier** [comment]
- advertise all : ok - need to check it actually uploads all node uri's to the redis server
- advertise client : fail - adds to the watchlist, but doesn't trigger
- advertise server : fail - adds to the watchlist, but doesn't trigger
- flip all : fail - adds to the watchlist, but doesn't trigger
- flip client : fail - adds to the watchlist, but doesn't trigger
- flip server : fail - adds to the watchlist, but doesn't trigger
- pull all :  fail - empty stubs
- pull client : fail - n/a
- pull server :  fail - n/a

**Comment by piyushk** [comment]
registering pubs/subs may not be enough (I've done this already). I think the callbacks in actionlib don't get fired correctly on occasion. Trying to figure out when this happens.

**Comment by stonier** [comment]
I started looking at this last night as well - I don't think I've gotten as far as you did and have not committed anything yet though. Do you have attempts as yet uncommitted?

I could have a look at this if you're stalled, or I could switch to work in parallel getting more remote gateway info on the redis server.

**Comment by piyushk** [comment]
Mostly what I've done is removed the empty stubs with the corresponding pubs/subs. Advertise and Pull are behaving as expected (tested manually through advertise_all and pull_all, automatically through all the calls). All of this has gotten merged, and I have nothing uncomitted.

Unfortunately, something is still amiss. Let's say you start a client and then pull in the server. The client's callbacks don't seem to fire. On the other hand, if you pull in the server and then start the client -- it seems to work. I haven't worked out what cases work or not, but actionlib depends on message callbacks, some of which may not be firing appropriately through the gateway paradigm.

I won't be able to take a look at this for the next day or two. If you want to take a look at it in this time, then go ahead. I might get back to this later when I try to do some multi-master control of the robots.

**Comment by stonier** [comment]
Ok, I'll take a look tonight.

**Comment by stonier** [comment]
I managed to get flips working, will look at pulls tomorrow. Didn't seem to run in to the same problems you had though. Some observations:
- It's not synchronising on both sides, so feedback channels and things only work on the remote side.
- I didn't bother getting complicated with the action abstraction, everything flipping, unflipping, registering and unregistering as pub subs as far as the remote end is concerned. Only the local worries about action client/server types.

**Comment by stonier** [comment]
Is the actionlib_tutorials averaging server/client actually working? It's bombastic for me. Testing only with the fibonacci now.

**Comment by piyushk** [comment]
I only tested through fibonacci.
