### ISSUE TITLE
Error re-adding public topic after topic publisher has been restarted with different uri

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#45]
Steps to reproduce bug:
- Follow the tutorial to add a topic to the public interface [here](http://redmine.robotconcert.org/projects/multimaster/wiki/Gateway_Development#Add-chatter-topic-as-a-public-interface)
- Terminate the /talker node. Till this step, the output of gateway is as expected (shown below).

Adding topic : /chatter,std_msgs/String,http://piyushk-desktop:51262/
Removing topic : /chatter,std_msgs/String,http://piyushk-desktop:51262/
- Restart the /talker node. get_topic_info.py will show updated port (as expected)
- Re-register /chatter topic based on new info.
- (BUG) cleanup thread instantly throws the topic out

Adding topic : /chatter,std_msgs/String,http://piyushk-desktop:55661/
Removing topic : /chatter,std_msgs/String,http://piyushk-desktop:55661/

The bug may not be in cleanup_thread.py. The rosnode.get_api_uri call [here](https://github.com/robotics-in-concert/rocon_multimaster/blob/master/multimaster_client/rocon_gateway_sync/src/rocon_gateway_sync/cleanup_thread.py#L93) will **always** return the uri for the first /talker node that is created. 

The code for get_api_uri suggests that it is not meant to be used across a persistent master instance (see the simplistic caching it uses [here](https://code.ros.org/trac/ros/browser/stacks/ros_comm/trunk/tools/rosnode/src/rosnode/__init__.py?rev=16363#L80)). Using master.lookupNode directly is a suitable alternative.

**Comment by jihoonl** [comment]
Awesome Thanks!

**Comment by piyushk** [comment]
Just realized that there are other places where the rosnode and the rostopic api have been used in a similar manner. I'll change all instances. Interestingly enough the rosservice api does not use caching, and is fine.

**Comment by piyushk** [comment]
This issue can now be closed, all offending code has been changed (in other re-writes). We'll have to keep in mind to not use rostopic.get_api or rosnode.get_api_uri, as they should not be called using a persistent master object.
