### ISSUE TITLE
flipout fails for hyphenated machine names

### ISSUE THREAD

**Issue by piyushk** [robotics-in-concert/rocon_multimaster#46]
While flipping out a service/topic, the components of the message are separated using hyphens. On the receivers side, the message is parsed incorrectly if extra hyphens exist in the message itself. I obtained this error as my machine name has a hyphen in it.

We'll have to improve the serialization/deserialization.

**Comment by jihoonl** [comment]
Yeah. I used '-' as a temporary solution to be distinct from ','  We should come up with better way of formatting the command message.

**Comment by piyushk** [comment]
It might be easy to load all the data into a dictionary, and use json or pickle to generate the serialized string to send and receive from redis.

**Comment by stonier** [comment]
We'll have to improve the serialization/deserialization - what do you mean by this piyush?

**Comment by piyushk** [comment]
I was thinking of using json to serialize data in dicts/lists to string,
and pass them over redis. It should remove some of the current problems
with using hyphens or commas as delimiters.
