### ISSUE TITLE
Monolithic 'request' service

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#48]
Just looking at that request service, it's starting to carry alot of 'services' inside the service.

JiHoon likes it simple. 

I tend to prefer splitting up services so they're easy to introspect and self contained, even if it means writing a few more lines of code.

It's not a point that assumes the level of importance of kimchi in one's diet though ;)

Thoughts?

**Comment by piyushk** [comment]
I would prefer splitting up the service. I believe once we consider various other things (flip_all, flip_all_public, pull_all), the number of services will greatly increase.

We might be able to find some middle ground, such as having separate services for public,flipped,pullled etc., but use add/remove/get/set as parameters to the service.

**Comment by stonier** [comment]
Yeah, thinking about it - one service makes it easy for the developer while split up services make it easy for the user to figure out what to hook up. That should be a no brainer - I'll sit down with Jihoon after Chuseok holiday and have a look at it.

**Comment by piyushk** [comment]
Sounds good. Here are my current thoughts on it. Hopefully this will help your discussion.

<service> <string command> <list>

Commands:
add
remove
get

Service names (with parallel for services):

public_topic_triple (currently add_public_topic etc. command) (add/remove/get)
public_topic (current add_named_topic etc. command) (add/remove/get - returns regex whitelist)
flipped_topic_triple (add/remove/get)
flipped_topic (add/remove/get)
foreign_topic_triple (add/remove/get)
foreign_topic (add/remove/get)

dump_all_topics (add/remove only)
flip_all_topics (add/remove only)
flip_all_public_topics (add/remove only)
pull_all_public_topics (add/remove only)

get_public_topics (get only - actual list/not regex)
get_flipped_topics (get only - actual list/not regex)
get_foreign_topics (get only - actual list/not regex)

**Comment by stonier** [comment]
I guess we've decided on this (i.e. no single service). We need to formally define the ros api now - #56.
