### ISSUE TITLE
Simple redis callback demo program

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#5]
Let's exactly see how the [pubsub](http://redis.io/topics/pubsub/) stuff on redis works.

**Comment by jihoonl** [comment]
A simple pub/sub example is test_redis a ros package in https://github.com/robotics-in-concert/rocon_multimaster.git
Instruction is redis wiki(http://redmine.robotconcert.org/projects/multimaster/wiki/Redis)
