### ISSUE TITLE
Unit testing conundrum

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#51]
Quickly getting to the point where we are going to have to work out some way to test this to make sure we don't break parts of it and so we can be confident all 100% of use cases are constantly covered and working.

I've never done anything beyond unit tests before (i.e. multiple ros systems, nodes). so will have to nut something out for this.

**Comment by piyushk** [comment]
Agreed. Some basic testing is certainly possible using the rostest framework, and we can start with those. At the same time, it might be a good idea to come up with a list of tests somewhere. We can split the list into local tests vs cross-master tests.

**Comment by stonier** [comment]
Lets start doing rostests in rocon_gateway_tests.

**Comment by piyushk** [comment]
Some basic testing reveals that we should be able to use the rostest framework as is. I'll try to churn out tests for the advertise call today.

**Comment by stonier** [comment]
Need a proper look at this still. Let's put this in v0.2. I think I'd like a proper testing environment, one which can easily spin up multiple ros systems, and get better feedback than that which ros unit tests provide.

Add that with network monitoring as the big tasks for v0.2.

**Comment by stonier** [comment]
We have an example graph.test to get things going in rocon_gateway_tests and a quick overview in 

https://github.com/robotics-in-concert/rocon_multimaster/blob/hydro-devel/rocon_test/Readme.md
