### ISSUE TITLE
Terminology

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#55]
Before things get too confusing, I think we need to settle on some terminology. Suggestions:
- `connection`: a pub/sub/service/action connection
- `remote`: reference to a gateway (or component thereof) on another ros master
- `advertise`: making a topic/service/action available to be freely pulled by remotes (put on the public interface).
- `flip`: directed tunnelling of a local topic/service/action through a specific remote gateway
- `pull`: registering a remote public topic/service/action on the local ros master
- `public interface`: list of publicly exposed topics/services/actions
- `flipped interface`: gateway name & list of topics/services/actions flipped to that gateway
- `pulled interface`: list of topic/service/action-gateway pairs pulled to the local system.
- `foreign interface`: list of gateway-topics/service/action pairs available locally 

The latter would be due to accepted flips from remote gateways or pulls from the local system.

Thoughts?

**Comment by piyushk** [comment]
This sounds good to me. remote and pull are fine.

**Comment by stonier** [comment]
Updated terminology back on the redmine wiki: http://redmine.robotconcert.org/projects/multimaster/wiki/Gateway_Model
