### ISSUE TITLE
Gateway Ros Api

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#56]
Confirming a ros api for the gateway. This carries over from #48.

Piyush's last comment:

Sounds good. Here are my current thoughts on it. Hopefully this will help your discussion.

`<service> <string command> <list>`

Commands:
- `add`
- `remove`
- `get`

Service names (with parallel for services):

public_topic_triple (currently add_public_topic etc. command) (add/remove/get)
public_topic (current add_named_topic etc. command) (add/remove/get - returns regex whitelist)
flipped_topic_triple (add/remove/get)
flipped_topic (add/remove/get)
foreign_topic_triple (add/remove/get)
foreign_topic (add/remove/get)

dump_all_topics (add/remove only)
flip_all_topics (add/remove only)
flip_all_public_topics (add/remove only)
pull_all_public_topics (add/remove only)

get_public_topics (get only - actual list/not regex)
get_flipped_topics (get only - actual list/not regex)
get_foreign_topics (get only - actual list/not regex)

**Comment by stonier** [comment]
Comments: 
- What would 'get' for a flipped_topic do?
- Can we combine flipped_topic flipped_service, flipped_action?
  - A bit like remap - doesn't care if it's a topic or a service
  - Are service triples significantly different from topic triples?
- Also need a 'list_remote_public_interfaces'

**Comment by piyushk** [comment]
'get' for 'flipped_topic' will return the current set of regex entries on a
per client basis. These regex entries comprise the whitelist that the
watcher thread monitors and flips/unflips topic_triples as they become
available/unavailable.

I'll need to go through the code tomorrow to figure out if we can combine
topics/services/actions. My gut instinct right now is that we'll run into
some problems with this. The ros manager handles the topic triples/service
triples differently for the time being, but everywhere else it should not
matter.

**Comment by piyushk** [comment]
I was looking into merging topics and services -- and it seems like for the most part it should be possible. I am definitely in the favor of it, as the code/api between topics/services seems a bit too redundant.

The only problem case is the master requires different information for topics/services -- which need to be 
Topic: (/topic,package/msg,host:port)
Service: (/service, host:port, host:port)

Consequently, the triples will always be different. At the same time, we can use this to our advantage and parse what type of triple it is based on a regex match. We can optionally support a 4-tuple as well, where the user can specify the type explictly.

We can merge topics/triples/quadruples into the same service - as all 3 are easily distinguishable. 

Based on your suggestions (and #55), here's an updated list:

/advertise [heterogeneous list of topics, regexs, triples, 4-tuples] _// triples/4-tuples are directly advertised, topics/regexs are placed on a watch list and updated with time_
/unadvertise [heterogeneous list of topics, regexs, triples, 4-tuples] _//we can rename this if necessary_
/advertise_mode all OR list
/get_advertised_interfaces  _//Returns both the regex list and the real interfaces published_

/flip [heterogeneous list of topics, regexs, triples, 4-tuples] [_optional_ [clients]] _//flip to all known clients if len(clients)=0_
/unflip [heterogeneous list of topics, regexs, triples, 4-tuples] [_optional_ [clients]]
/flip_mode all OR public OR list (optional [clients])
/get_flipped_interfaces _//Returns both the regex list and the real interfaces flipped on a per client basis_

/register_remote [heterogeneous list of triples, 4-tuples]
/unregister_remote [heterogeneous list of triples, 4-tuples]
/pull [heterogeneous list of topics, regexs] [_optional_ [clients]]
/stop_pull [heterogeneous list of topics, regexs] [_optional_ [clients]]
/pull_mode all OR list (optional [clients])
/get_pulled_interfaces _//Returns both the regex list and the real interfaces pulled on a per client basis_

/list_remote_interfaces

Thoughts?

**Comment by stonier** [comment]
Continued and finalising over at the [review](http://ros.org/wiki/rocon_multimaster/Reviews/Gateway_API_Review%20-%20Oct%202012).
