### ISSUE TITLE
How does redis TTL work?

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#6]
I've seen Ken talking about this, I've also seen it specifically on the redis issue tracker. Exactly what is this about?

**Comment by drzaiusx11** [comment]
http://redis.io/commands/ttl

The idea is that when you register a resource, it has to be periodically set otherwise it expires. hope this helps!

**Comment by stonier** [comment]
Thanks for the link jeff - just hadn't gotten around to digging this up yet.

Probably looks useful for generating the network statistics for clients. I wonder if we can connect callbacks to the expiration of a ttl resource.

**Comment by stonier** [comment]
Jeff added a link in #10...connecting callbacks to ttl expirations may not quite be there yet:
- http://code.google.com/p/redis/issues/detail?id=360

**Comment by stonier** [comment]
Archiving.
