### ISSUE TITLE
Flipping Implementation

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#62]
Start working on a flipping implementation as outlined in the [review](http://ros.org/wiki/rocon_multimaster/Reviews/Gateway_API_Review%20-%20Oct%202012).

Most important points that need addressing:
- /flip, /flip_pattern, /flip_all services
- Remapping
- Drop triples from the user perspective, names/names+node names instead.
- Regex handling
- Practical watchlist/blacklist handling

**Comment by stonier** [comment]
**Remapping**

After commit 8edf98fb43d39415a1e143d9ceb5f4b4cb05f65d, everythign gets setup up, but remapping is a problem, /chatter -> /gateway##/chatter sets up the node and all, but a rostopic echo doesn't pick up anything.

If we change master_api.py:184:

```
  node_master.registerPublisher(registration.local_name,registration.type_info,registration.xmlrpc_uri)
```

to

```
  node_master.registerPublisher(registration.remote_name,registration.type_info,registration.xmlrpc_uri)
```

everything works.

**Comment by stonier** [comment]
Node uri's are just that, node uri's. Any connection between pubs and subs from one process to another shunts along the same pair of node uri's, i.e. one socket for all pubsub communications between two processes. Which means, any messaging shunting down the socket needs the topic name as an identifier to uniquely distinguish it from other topic messages going down the same socket.

Damn disappointing!

**Comment by stonier** [comment]
I feel like a naive noob now as well....

Still, it's not a showstopper. Can control the remaps from the application manager side and make sure we specify the remaps before we launch, rather than when sending the flips.

**Comment by stonier** [comment]
Actually, should we insert relays if the user specifically asks for a remapping?

**Comment by piyushk** [comment]
This was unfortunate.

This seems like a plausible option. There are a few questions to ask here
1) Is there a benefit in getting the gateway to automatically instantiate
the relay given the mapping vs the user being directly responsible for
launching the relay and passing information appropriately to the gateway.
The only benefit I see is a static remapping selected by the user(i.e.
/robot1/) vs dynamic remapping by the gateway (i.e. /gatewayXX/(
2) If there are colliding names, a pull request won't be able to do the
relay at its end. Should the advertise call do the remapping?

**Comment by stonier** [comment]
Though it would have been convenient to do dynamic remappings across multimaster, to be honest, I don't want relays getting thrown in. If we can workaround it by getting app manager to remap when launching an app (and its environment), then we don't have a use case for it right now. The only benefit would be for people not using an app manager like infrastructure on top. 

And for those people, we can probably more easily write a convenient script which can set up a relay and call the gateway on the relay in one shot (much easier than putting that all in the gateway). Call it 'remapped_flip' or some such.

Do you have a use case?

**Comment by stonier** [comment]
5638745d0ff08b8a9f8749a2a477d588231c823f bigfixes the watcher on a flip's source connection.

**Comment by stonier** [comment]
Needs to unflip the buggers when the gateway closes.

**Comment by stonier** [comment]
One jobs left that I can think of:
- Deactivate flips if a remote gateway disappears
