### ISSUE TITLE
Redis server on android

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#7]
I don't think this will be possible - which is a bit of a conundrum, since we'd like the centralised building manager eventually to be running on such a tablet.

**Comment by jihoonl** [comment]
One guy is currently porting Redis Android NDK. Basic functionality is done already - Reference(http://rikiji.it/post/36)
It uses a Jedis as client library.

However, as we discussed, making tablet as server would not be a good idea in my opinion

**Comment by stonier** [comment]
I concur - added information on the [wiki](http://redmine.robotconcert.org/projects/multimaster/wiki/Redis).
