### ISSUE TITLE
Remote gateway list in remote_gateway_info

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#73]
Could split it out later, but put it in the gateway_info for now.

Then fix up flip_chatter test so it automagically finds an unused gateway to flip to. Damn annoying having to set the gateway all the time.

**Comment by piyushk** [comment]
I have the remote gateway list setup already. Will commit it in today's merge. I was using it to write rostests for the advertise call.

**Comment by stonier** [comment]
Looks good - can you send a pull request on rocon_comms for me? I've not got your remote gateway related comms.
