### ISSUE TITLE
Test the rosgraph masterapi scripts

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#8]
You might like to test the rosgraph master api scripts in rocon_gateway_sync/scripts. Specifically  `show_node_xmlrpc_uri.py` and `register_publisher.py`.

These show how to use the rosgraph master api (xmlrpc node underneath) to flip across a publisher from a remote system to the local master. We'll need to implement these inside the local manager sync.

Comments are in register_publisher.py to show how to setup the environment with two roscores and run the scripts.

**Comment by jihoonl** [comment]
All flipping topic/service are achievable using rosmaster api
