### ISSUE TITLE
Check regex matching

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#80]
I think the public interface regex might fail in some cases, e.g. matching `.*te` would fail to match `/chatter`.

I think we need to check for a match and then make sure the match lengths are identical to ensure it matches the whole name. I put this in flipped_interface.py

```
match_result = re.match(rule.connection.name, name)
if match_result and match_result.end() == len(name):
```

**Comment by piyushk** [comment]
Thanks for pointing this out.

**Comment by stonier** [comment]
I actually switched it to use .group(), it's a little bit less obscure than comparing lengths.

Also, did you plan on regex'ing node variables?

**Comment by piyushk** [comment]
I am. It's only a couple of lines of code-change. I'll submit it with the
next pull request.

Piyush
