### ISSUE TITLE
More Remote Gateway Info

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#84]
Currently showing gateway names and public interfaces which are parsed from the gateway hub (redis server). 

Do we want to publicly declare what `flipped_connections`, `flip_watchlist`, `flipped_in_connections` and `pulled_connections` each gateway has as well? 

Could be very useful for debugging from a central location.

**Comment by piyushk** [comment]
I was thinking about this. If anyone can retrieve the pieces you have mention for any arbitrary gateway, isn't privacy being violated?

**Comment by stonier** [comment]
I thought the same too...privacy is only partially being violated. You're letting people see a little bit of what's happening inside but you still do not let them _do_ anything.

I'd rather not do it, but just the idea of being able to quickly scan what's where in all the gateways from one source instead of ssh'ing into each robot to work it out is so practically useful.

At the very least, a gateway should provide information about whether it's _firewalling_ flips or not.

Also, we could disable something like this by default and have a ros parameter to optionally make the information public.

**Comment by piyushk** [comment]
If a remote gateway gets the information about a connection, could it simply not register the information with its local master? Is there a way to firewall this?

Strongly agree with the ros parameter thing

**Comment by stonier** [comment]
I wouldn't be exposing service or node uri's for flipped in connections in the remote gateway info, just 1) the gateway they flipped from 2) the topic name, 3) the node name. Debugging information only.

For flipping, the only time that service and node uri's hit the network is when flip requests are made, on the redis pubsub channels. Which in future, if we really want to secure things, then we'll have to encode those messages or something similar.

I'm not in a rush to provide security yet though - my first target is just to simplify things for the higher level, not secure things, but at least have a design that can move in that direction easily. The main problem for security with ros comms is they operate on any available port - you can't restrict a port range that they operate on. That is something they tried in Darc, and something I'll ask for when they start redesigning next gen comms for ros.

**Comment by piyushk** [comment]
This sounds good. The information would certainly be useful. I would recommend modifying the GatewayInfo and RemoteGatewayInfo services to use a common Gateway object internally.

**Comment by stonier** [comment]
added pulled interface information.... d0d4c04
