### ISSUE TITLE
Refactoring basic message types and classes

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#87]
Can we dump service_uri, topic_type, uri from the basic Connection object?

The user doesn't actually ever need to use or even see these, so let's get them out of the way.

Perhaps create a class inheriting connection to store all the details for a publicly exposed and available interface (like my utils.Registration class), or create another .msg explicitly for that purpose.

This may touch a fair bit of code in the advertising section though...

**Comment by piyushk** [comment]
This is a good point. I'll switch advertisements to use utils.Registration
internally. The user doesn't have to see these values at any point, so it
doesn't need to be inside a msg.

**Comment by stonier** [comment]
You're going to have to splash uri's on the redis server though - and that advertisement information isn't really a registration per se (that's part of pulling). Differences in information between the concepts:

**Connection**
- name
- node
- type

**Advertisement**
- Connection
- type_info (topic_type or service_uri)
- node_uri

**Registration**
- gateway
- Connection (the remote connection)
- type_info (topic_type or service_uri)
- node_uri
- local node (anonymously generated)

**Flip**
- gateway
- Connection

**Comment by piyushk** [comment]
Ok. We'll need a new type, something that can be returned by master_api.getConnectionState. How about:

**User Visible i.e. ROS messages**

**Connection -> rename to Rule**
- name
- node
- type

**FlipRule -> rename to RemoteRule** _Used by both flip and pull calls_
- Rule
- gateway

**Internal**

**utils.Connection** _Used for advertisement, as well as returned by getConnectionState. This information is serialized and put on redis_
- Rule
- type_info (topic_type or service_uri)
- node_uri

**utils.Registration** _Used once a connection has been  flipped or pulled_
- utils.Connection
- local_node
- node_uri

Let me know what you think. 

I need to teach right now, so I won't be able to make many changes before you guys are awake anyway. This change won't be too bad, but will be across the board - so it should be better for a single person to do it.

**Comment by stonier** [comment]
That looks like a good set of definitions to me. 

I have only a small amount of time this morning, but then will be busy on other things until Sunday. If you want to tackle this, great. If you don't get time, I'll attack it on Sunday.

**Comment by piyushk** [comment]
I can take a crack at it. I would like to develop a basic app on top of
this for my setup by this weekend.

Piyush
