### ISSUE TITLE
Merge flipped and pulled interfaces 

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#90]
Piyush reckons there's alot of common code here. 

Merge them as far as we can.

**Comment by piyushk** [comment]
A couple of notes about this:
1. I tried to keep the modification to flipped_interface as less as possible when constructing pulled_interface. This ensures the diff captures only the key elements. The comments/names in pulled interface don't make much sense right now.
2. The modifications to pulled interface were done in such a way that the flipped interface functioning should not be affected. It can be used as is for both after renaming things appropriately.

**Comment by stonier** [comment]
Yeah, it looks good. I'll start writing a parent class shortly.
