### ISSUE TITLE
Redis Configuration on Multiple Machines

### ISSUE THREAD

**Issue by stonier** [robotics-in-concert/rocon_multimaster#91]
From Piyush:

For some reason the default configuration in redis 2.2.2 (the one we
get through apt-get in 12.04) is incorrect. The default configuration
in 2.2.2 should have the following (/etc/redis/redis.conf)

```
# If you want you can bind a single interface, if the bind option is not
# specified all the interfaces will listen for incoming connections.
#
bind 127.0.0.1
```

The above bind SHOULD be commented:

```
# bind 127.0.0.1
```

If the bind is enabled, redis doesn't listen on the public interfaces,
and you can't run the framework on separate machines. It took me far
longer to debug this error than it should have. After this correction
is made, you can restart redis using init.d.

**Comment by stonier** [comment]
I guess they've restricted it for security reasons since we don't use a password to log in. We'll have to address that 'security' issue ultimately.

For now we can put another check in the gateway hub script (it already checks for redis daemon and avahi existence) and provide a fatal error and some advice to the user on correcting the problem. Probably make our own script the user can sudo.

**Comment by stonier** [comment]
An interesting thought, especially since this design started around redis:

1) We could easily remove all redis pubsubs and replace them with a single or a few ros pubs/subs/services that are shared and pulled to enable the gateway communications (flips, unflips, pulls, etc).

2) Put a single xmlrpc node in front of the redis server to handle redis insertions/deletions.

That way we resolve the security issue, yet keep the simple centralised design. Maybe a good plan for v2.

**Comment by piyushk** [comment]
I actually think our current usage is fine, as indicated by the redis forum. The latest redis version does not have this restriction, nor could I find any mention of it. I think the restriction was an accident, and got passed on the the ubuntu distro.

**Comment by stonier** [comment]
I'm not really thinking of getting around the exact problem as stated above. Just thinking out loud that the redis server is sitting out in the open with it's port publicly announced on zeroconf. If we were to worry about security at some point in time, then anybody can mess with the system since they have full access to manipulation on the redis store.

As I said though, not a huge priority, just would like to be able to say we can close that hole quickly if necessary.

**Comment by stonier** [comment]
I'm going to run our own private redis server. Shouldn't be too hard - populate a redis.conf.template from ros param variables and see if a normal user can make use of that.

**Comment by piyushk** [comment]
+1 on our own redis server.

**Comment by stonier** [comment]
Redis server configuration using the following params:
- port
- maximum memory (using default of 10mb)

It also disables save to disk, databases (we don't use anyway).

Some features we might like to set
- password - we might implement that some time in the future.
- timeout - how long before the server is considered stale and shutdown (default is 300s).
